site_name: HiPer Bridge
site_url: https://steve-xmh.github.io/hb/
repo_name: Steve-xmh/HiPerBridge
repo_url: https://github.com/Steve-xmh/HiPerBridge
edit_uri: ''
dev_addr: '127.0.0.1:2546'

extra_css:
  - stylesheets/main.css

theme:
  name: material
  language: zh
  logo: assets/hb-icon-flat.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    repo: fontawesome/brands/github

nav:
  - 主页: index.md

